site_name: seq-collection
theme: readthedocs
repo_url: https://github.com/danielecook/seq-collection


markdown_extensions:
    - admonition
    - smarty
    - toc:
            permalink: true
            separator: _
    - fenced_code
    - sane_lists

nav:
    - Home: index.md
    - FASTA:
        - fa-gc: fa-gc.md
    - FASTQ:
        - fq-count: fq-count.md
        - fq-dedup: fq-dedup.md
        - fq-meta: fq-meta.md
    - BAM:
        - insert-size: insert-size.md
        - read-count: read-count.md
    - VCF:
        - json: json.md
        - sample: sample.md
    - MULTI:
        - iter: iter.md
        - rand: rand.md


extra_css:
    - styles.css